1 create redis terraform module
opsd-io/terraform-module-digitalocean-redis pull request #3
Opened 2024-03-21 11:43 UTC by jakub-kubera

## What changes does your PR bring?

In a few words, describe what changes your commits make to the code.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (non-breaking change to the build process or auxiliary tools)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation (Improvements or additions to documentation)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)

## References

Fixes:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2024-04-08 11:36 UTC, michaltomczuk commented
Readme file is missing in the example

2024-04-12 08:15 UTC, stawii requested changes

2024-04-12 08:15 UTC, stawii commented on .github/PULL_REQUEST_TEMPLATE.md
Don't change template in PR.

2024-04-12 08:15 UTC, stawii commented on README.md
> +module "terraform-module-digitalocean-redis" {
Simplify name, "do_redis", "redis_cluster" or generic "example". And please use `_`  not `-`.

2024-04-12 08:15 UTC, stawii commented on README.md
> +module "terraform-module-digitalocean-redis" {
The `source` is missing.

2024-04-12 08:15 UTC, stawii commented on examples/create_redis_database/terraform.tf
> +  required_providers {
RTFM. Separate block from arguments with single empty line.

2024-04-12 08:15 UTC, stawii commented on main.tf
> +resource "digitalocean_database_firewall" "main" {
RTFM. Separate resources with single empty line.

2024-04-12 08:15 UTC, stawii commented on main.tf
> +resource "digitalocean_database_cluster" "main" {
RTFM. Separate resources with single empty line.

2024-04-12 08:15 UTC, stawii commented on outputs.tf
> +output "main_host_id" {
I'm not sure if `main_` and `redis_` prefixes are needed in outputs. Please rethink this.

2024-04-12 08:15 UTC, stawii commented on versions.tf
RTFM. The terraform block in modules should be at beginning of the main.tf file.
Don't forget about empty line before `required_providers` block ;)

2024-04-12 08:51 UTC, jakub-kubera reviewed
applied changes

2024-04-19 09:35 UTC, stawii approved these changes

2024-04-19 12:08 UTC, merged